base_images:
  golangci-lint:
    name: golangci-lint
    namespace: ci
    tag: v1.37.1
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
images:
- dockerfile_path: Dockerfile.build
  from: src
  to: assisted-events-stream-build
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit-test
  commands: make unit-test
  container:
    from: assisted-events-stream-build
- as: lint
  commands: |
    export GOCACHE=/tmp/
    export GOLANGCI_LINT_CACHE=/tmp/.cache
    export GOPROXY=https://proxy.golang.org
    go mod tidy
    go mod vendor
    make lint
  container:
    clone: true
    from: golangci-lint
  skip_if_only_changed: ^\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|OWNERS_ALIASES|LICENSE)$
zz_generated_metadata:
  branch: master
  org: openshift-assisted
  repo: assisted-events-stream
